---
- name: Install NAS packages
  ansible.builtin.apt:
    name: "{{ nas_packages }}"
    state: present
    update_cache: true

- name: Configure /etc/exports
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    mode: "0644"
  notify: reload nfs
